version: '3.7'

services:
  # nginx:
  #  image: ray-nginx-local:latest
  #  ports:
  #    - 2055:80

  redis:
    container_name: "ray_redis"
    image: redis:alpine
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    sysctls:
      net.core.somaxconn: 65535
    command: "/bin/sh -c redis-server & echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc.local"

  postgres:
    container_name: "ray_postgres"
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=RaysX
      - POSTGRES_PASSWORD=RaysX
      - POSTGRES_USER=RaysX
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  default:
    name: "ray"

volumes:
  redis:
    name: "ray_redis"
    # external: true
  pg-data:
    name: "ray_postgres"
