version: '3.7'

services:

  nginx:
    image: bardakdev/ray-client
    restart: always
    links:
      - backend
    ports:
      - "80:80"
    privileged: true

  backend:
    image: bardakdev/ray
    restart: always
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
      - postgres
      - rabbitmq
      - minio
    volumes:
      - media:/usr/src/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo-db:/data/db
      - mongo-db-config:/data/configdb

  redis:
    image: redis:alpine
    restart: always
    privileged: true
    volumes:
      - redis:/data
    sysctls:
      net.core.somaxconn: 65535
    command: "/bin/sh -c redis-server & echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc.local"

  postgres:
    container_name: hb_postgres
    image: postgres:15
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_DB=HummingBot
      - POSTGRES_PASSWORD=HummingBot
      - POSTGRES_USER=HummingBot
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: hb_rabbitmq
    image: bardakdev/rabbitmq
#    ports:
#      - "1883:1883"
    volumes:
      - rabbitmq-conf:/etc/rabbitmq/conf.d:ro
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5

  minio:
    container_name: hb_minio
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: HummingBot
      MINIO_ROOT_PASSWORD: HummingBot
    command: server --console-address ":9001" /data

networks:
  default:
    name: "ray"

volumes:
  mongo-db:
    name: "ray_mongo-db"
    external: true
  mongo-db-config:
    name: "ray_mongo-db-config"
  redis:
    name: "ray_redis"
  media:
    name: "ray_media"
  pg-data:
    name: "hb.postgres"
  minio-data:
    name: "hb.minio"
  rabbitmq-data:
    name: "hb.rabbitmq.data"
  rabbitmq-conf:
    name: "hb.rabbitmq.conf"